[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "0.12", features = [ "glsl" ], path="../wgpu/wgpu" }
env_logger = "0.9.0"
bytemuck = "1.9.1"
pollster = "0.2.5"
rayon = "1.5.2"
plonky2_field = { git = "https://github.com/mir-protocol/plonky2.git" }
